# Generated by Django 2.1.2 on 2018-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
