# Generated by Django 2.1.5 on 2019-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='static/None/no-img.jpg', upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
