# Generated by Django 2.1.5 on 2019-01-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190106_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/no-img.jpg', upload_to='uploads/'),
        ),
    ]
